apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0d7166e48bb2fb5cb #TODO: CHANGE TO DYNAMIC FS, HAS TO BE MANUALLY CHANGED EVERY TIME
  directoryPerms: "750"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/dynamic_provisioning"
volumeBindingMode: Immediate
